// <copyright file="Leaderboards.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using System.Collections.Generic;
    using Internal;

    /// <summary>
    /// Provides access to leaderboards registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Leaderboards
    {
        private static readonly UnifiedLeaderboard s_ascendBallHighScore = new UnifiedLeaderboard("AscendBallHighScore",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "com.ascendball.leaderboard"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIh5TAsZEREAIQAA"
#else
            "AscendBallHighScore"
#endif
            );

        public static UnifiedLeaderboard AscendBallHighScore
        {
            get { return s_ascendBallHighScore; }
        }

        private static readonly UnifiedLeaderboard s_colorShiftHighScore = new UnifiedLeaderboard("ColorShiftHighScore",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "com.colorshift.leaderboard"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIh5TAsZEREAIQAQ"
#else
            "ColorShiftHighScore"
#endif
            );

        public static UnifiedLeaderboard ColorShiftHighScore
        {
            get { return s_colorShiftHighScore; }
        }

        private static readonly UnifiedLeaderboard s_dropBallHighScore = new UnifiedLeaderboard("DropBallHighScore",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "com.dropball.leaderboard"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIh5TAsZEREAIQAg"
#else
            "DropBallHighScore"
#endif
            );

        public static UnifiedLeaderboard DropBallHighScore
        {
            get { return s_dropBallHighScore; }
        }

        public static string GetPlatformID(string internalId)
        {
            return s_leaderboardDictionary.ContainsKey(internalId)
                ? s_leaderboardDictionary[internalId].ID
                : string.Empty;
        }

        private static readonly Dictionary<string, UnifiedLeaderboard> s_leaderboardDictionary = new Dictionary<string, UnifiedLeaderboard>
        {
            { "AscendBallHighScore", s_ascendBallHighScore },
            { "ColorShiftHighScore", s_colorShiftHighScore },
            { "DropBallHighScore", s_dropBallHighScore }
        };
    }
}
